package com.yicai.trade.module.content.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "t_news")
@EntityListeners(AuditingEntityListener.class)
@EqualsAndHashCode(of = {"id"})
public class News {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "news_no", unique = true, length = 30)
    private String newsNo;

    @Column(nullable = false, length = 200)
    private String title;

    @Column(length = 500)
    private String summary;

    @Column(columnDefinition = "TEXT")
    private String content;

    @Column(name = "cover_image", length = 500)
    private String coverImage;

    @Column(length = 50)
    @Builder.Default
    private String category = "NEWS";  // NEWS, ANNOUNCEMENT, POLICY

    @Column(name = "view_count")
    @Builder.Default
    private Integer viewCount = 0;

    @Column(name = "is_top")
    @Builder.Default
    private Boolean isTop = false;

    @Column(name = "is_recommend")
    @Builder.Default
    private Boolean isRecommend = false;

    @Column(length = 20)
    @Builder.Default
    private String status = "DRAFT";  // DRAFT, PUBLISHED, ARCHIVED

    @Column(name = "publish_time")
    private LocalDateTime publishTime;

    @Column(name = "author_id")
    private Long authorId;

    @Column(name = "author_name", length = 50)
    private String authorName;

    /** 语言 (zh / en) */
    @Column(length = 10)
    @Builder.Default
    private String lang = "zh";

    /** 关联行业品类ID */
    @Column(name = "industry_id")
    private Long industryId;

    /** 冗余行业名称（英文） */
    @Column(name = "industry_name", length = 100)
    private String industryName;

    /** 是否AI自动生成 */
    @Column(name = "auto_generated")
    @Builder.Default
    private Boolean autoGenerated = false;

    @CreatedDate
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
