package com.yicai.trade.module.content.dto;

import lombok.Data;
import java.time.LocalDateTime;

@Data
public class NewsResponse {
    private Long id;
    private String newsNo;
    private String title;
    private String summary;
    private String content;
    private String coverImage;
    private String category;
    private Integer viewCount;
    private Boolean isTop;
    private Boolean isRecommend;
    private String status;
    private LocalDateTime publishTime;
    private String authorName;
    private String lang;
    private Long industryId;
    private String industryName;
    private Boolean autoGenerated;
    private LocalDateTime createdAt;
}
